- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t 2048-game .
      args:
        chdir: /var/lib/jenkins/workspace/2048-game

    - name: tag image
      command: docker tag 2048-game gyenoch/2048-game:latest

    - name: Retrieve Docker credentials from AWS Secrets Manager
      aws_secretsmanager:
      secret_name: "docker_credentials"
      register: docker_credentials

    - name: Log in to Docker Hub
      community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: "{{ docker_credentials.secret['docker_username'] }}"
      password: "{{ docker_credentials.secret['docker_password'] }}"

    - name: Push image
      command: docker push gyenoch/2048-game:latest

    - name: Run container
      command: docker run -d --name 2048-game -p 80:80 gyenoch/2048-game:latest
