name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'variables.tfvars'
      action:
        type: choice
        description: 'Choose plan, apply, or destroy'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'plan'

jobs:
  terraform:
    name: Terraform Plan, Apply, or Destroy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./EC2-TF

    - name: Validate Terraform
      run: terraform validate
      working-directory: ./EC2-TF

    - name: Plan Terraform
      id: plan
      run: terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -out=tfplan
      working-directory: ./EC2-TF

    - name: Apply Terraform
      if: github.event.inputs.action == 'apply' && github.ref == 'refs/heads/main'
      run: |
        terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -out=tfplan
        terraform apply -auto-approve tfplan
      working-directory: ./EC2-TF

    - name: Save Terraform Plan
      if: github.event.inputs.action == 'plan' && github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: ./EC2-TF/tfplan

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform destroy -var-file=${{ github.event.inputs.tfvars_file }} -auto-approve
      working-directory: ./EC2-TF
